version: '3'

tasks:
  default:
    cmds:
      - rm -rf build
      - cmake .
      - make
      - bin/suite_1_app
  build:
    cmds:
      - rm -rf build
      - gengetopt --output-dir cli < cli/cli.ggo
      - cmake .
      - make
